### ISSUE TITLE
Device not showing as a com on windows machines

### ISSUE THREAD

**Issue by mn3na3a** [xjtuecho/CMSIS-DAP#1]
hey, thanks for the great effort.
i've tried the custom firmware on a linux machine and it is identified and works with no problem on a guest os running in a virtual machine. the problem appeared when i tried to connect to a host machine that is running windows 8.1/10. the device is recognized in `HID` section and keil doesn't detect it. is there is something i need to do for the device to be recognized correctly?

**Comment by xjtuecho** [comment]
> hey, thanks for the great effort.
> i've tried the custom firmware on a linux machine and it is identified and works with no problem on a guest os running in a virtual machine. the problem appeared when i tried to connect to a host machine that is running windows 8.1/10. the device is recognized in `HID` section and keil doesn't detect it. is there is something i need to do for the device to be recognized correctly?

sorry, The firmware was created and tested on windows 7 x64. Windows 8.1/10 are not tested.
